# Generated by Django 5.1.4 on 2024-12-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perguntas',
            name='dificuldade',
            field=models.CharField(choices=[('Muito Facil', 'Muito Facil'), ('Facil', 'Facil'), ('Intermediário', 'Intermediário'), ('Dificil', 'Dificil'), ('Muito Dificil', 'Muito Dificil')], default=0, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perguntas',
            name='fase',
            field=models.CharField(choices=[('1', 'Fase 1'), ('2', 'Fase 2'), ('3', 'Fase 3'), ('4', 'Fase 4'), ('5', 'Fase 5'), ('6', 'Fase 6'), ('7', 'Fase 7'), ('8', 'Fase 8'), ('9', 'Fase 9'), ('10', 'Fase 10'), ('11', 'Fase 11'), ('12', 'Fase 12'), ('13', 'Fase 13'), ('14', 'Fase 14'), ('15', 'Fase 15'), ('16', 'Fase 16')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
