# Generated by Django 5.1.4 on 2024-12-07 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_perguntas_dificuldade_perguntas_fase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perguntas',
            options={'verbose_name_plural': 'Perguntas'},
        ),
        migrations.AlterModelOptions(
            name='userperfil',
            options={'verbose_name': 'Perfil de úsuario'},
        ),
        migrations.AddField(
            model_name='userperfil',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perguntas',
            name='dificuldade',
            field=models.CharField(choices=[('Muito Facil', 'Muito Facil'), ('Facil', 'Facil'), ('Intermediário', 'Intermediário'), ('Difícil', 'Difícil'), ('Muito Difícil', 'Muito Difícil')], max_length=13),
        ),
    ]
