# Generated by Django 5.1.3 on 2024-12-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_perguntas_options_alter_userperfil_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userperfil',
            name='categoria',
            field=models.CharField(choices=[('Cordas', 'Cordas'), ('Madeiras', 'Madeiras'), ('Metais', 'Metais')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
