# Generated by Django 5.1.3 on 2024-12-13 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0004_userperfil_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userperfil',
            name='cargo',
        ),
        migrations.AddField(
            model_name='userperfil',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
