# Generated by Django 5.1.3 on 2024-12-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_userperfil_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Terminado em'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
    ]
