# Generated by Django 5.1.3 on 2024-12-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_jogo_finished_at_alter_jogo_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
