# Generated by Django 5.1.3 on 2024-12-23 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_jogo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perguntas',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.userperfil'),
        ),
        migrations.AlterField(
            model_name='perguntas',
            name='fase',
            field=models.CharField(choices=[('1', 'Fase 1'), ('2', 'Fase 2'), ('3', 'Fase 3'), ('4', 'Fase 4'), ('5', 'Fase 5'), ('6', 'Fase 6'), ('7', 'Fase 7'), ('8', 'Fase 8'), ('9', 'Fase 9'), ('10', 'Fase 10'), ('11', 'Fase 11'), ('12', 'Fase 12'), ('13', 'Fase 13'), ('14', 'Fase 14'), ('15', 'Fase 15'), ('16', 'Fase 16'), ('N/D', 'Sem Fase')], max_length=10),
        ),
    ]
